const data = [
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecef8',
    },
    'Patient Number': '1',
    'State Patient Number': 'KL-TS-P1',
    'Date Announced': '30/01/2020',
    'Age Bracket': '20',
    Gender: 'F',
    'Detected City': 'Thrissur',
    'Detected District': 'Thrissur',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '14/02/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecef9',
    },
    'Patient Number': '2',
    'State Patient Number': 'KL-AL-P1',
    'Date Announced': '02/02/2020',
    'Detected City': 'Alappuzha',
    'Detected District': 'Alappuzha',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '14/02/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecefa',
    },
    'Patient Number': '3',
    'State Patient Number': 'KL-KS-P1',
    'Date Announced': '03/02/2020',
    'Detected City': 'Kasaragod',
    'Detected District': 'Kasaragod',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '14/02/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecefb',
    },
    'Patient Number': '4',
    'State Patient Number': 'DL-P1',
    'Date Announced': '02/03/2020',
    'Age Bracket': '45',
    Gender: 'M',
    'Detected City': 'East Delhi (Mayur Vihar)',
    'Detected District': 'East Delhi',
    'Detected State': 'Delhi',
    'State code': 'DL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '15/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecefc',
    },
    'Patient Number': '5',
    'State Patient Number': 'TS-P1',
    'Date Announced': '02/03/2020',
    'Age Bracket': '24',
    Gender: 'M',
    'Detected City': 'Hyderabad',
    'Detected District': 'Hyderabad',
    'Detected State': 'Telangana',
    'State code': 'TG',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '02/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecefd',
    },
    'Patient Number': '6',
    'Date Announced': '03/03/2020',
    'Age Bracket': '69',
    Gender: 'M',
    'Detected City': 'Jaipur',
    'Detected District': 'Italians',
    'Detected State': 'Rajasthan',
    'State code': 'RJ',
    'Current Status': 'Recovered',
    Nationality: 'Italy',
    'Status Change Date': '03/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecefe',
    },
    'Patient Number': '7',
    'Date Announced': '04/03/2020',
    'Age Bracket': '55',
    'Detected City': 'Gurugram',
    'Detected District': 'Italians',
    'Detected State': 'Haryana',
    'State code': 'HR',
    'Current Status': 'Recovered',
    Nationality: 'Italy',
    'Status Change Date': '29/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10becceceff',
    },
    'Patient Number': '8',
    'Date Announced': '04/03/2020',
    'Age Bracket': '55',
    'Detected City': 'Gurugram',
    'Detected District': 'Italians',
    'Detected State': 'Haryana',
    'State code': 'HR',
    'Current Status': 'Recovered',
    Nationality: 'Italy',
    'Status Change Date': '29/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf00',
    },
    'Patient Number': '9',
    'Date Announced': '04/03/2020',
    'Age Bracket': '55',
    'Detected City': 'Gurugram',
    'Detected District': 'Italians',
    'Detected State': 'Haryana',
    'State code': 'HR',
    'Current Status': 'Recovered',
    Nationality: 'Italy',
    'Status Change Date': '29/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf01',
    },
    'Patient Number': '10',
    'Date Announced': '04/03/2020',
    'Age Bracket': '55',
    'Detected City': 'Gurugram',
    'Detected District': 'Italians',
    'Detected State': 'Haryana',
    'State code': 'HR',
    'Current Status': 'Recovered',
    Nationality: 'Italy',
    'Status Change Date': '29/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf02',
    },
    'Patient Number': '11',
    'Date Announced': '04/03/2020',
    'Age Bracket': '55',
    'Detected City': 'Gurugram',
    'Detected District': 'Italians',
    'Detected State': 'Haryana',
    'State code': 'HR',
    'Current Status': 'Recovered',
    Nationality: 'Italy',
    'Status Change Date': '29/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf03',
    },
    'Patient Number': '12',
    'Date Announced': '04/03/2020',
    'Age Bracket': '55',
    'Detected City': 'Gurugram',
    'Detected District': 'Italians',
    'Detected State': 'Haryana',
    'State code': 'HR',
    'Current Status': 'Recovered',
    Nationality: 'Italy',
    'Status Change Date': '29/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf04',
    },
    'Patient Number': '13',
    'Date Announced': '04/03/2020',
    'Age Bracket': '55',
    'Detected City': 'Gurugram',
    'Detected District': 'Italians',
    'Detected State': 'Haryana',
    'State code': 'HR',
    'Current Status': 'Recovered',
    Nationality: 'Italy',
    'Status Change Date': '29/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf05',
    },
    'Patient Number': '14',
    'Date Announced': '04/03/2020',
    'Age Bracket': '55',
    'Detected City': 'Gurugram',
    'Detected District': 'Italians',
    'Detected State': 'Haryana',
    'State code': 'HR',
    'Current Status': 'Recovered',
    Nationality: 'Italy',
    'Status Change Date': '29/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf06',
    },
    'Patient Number': '15',
    'Date Announced': '04/03/2020',
    'Age Bracket': '55',
    'Detected City': 'Gurugram',
    'Detected District': 'Italians',
    'Detected State': 'Haryana',
    'State code': 'HR',
    'Current Status': 'Recovered',
    Nationality: 'Italy',
    'Status Change Date': '29/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf07',
    },
    'Patient Number': '16',
    'Date Announced': '04/03/2020',
    'Age Bracket': '55',
    'Detected City': 'Gurugram',
    'Detected District': 'Italians',
    'Detected State': 'Haryana',
    'State code': 'HR',
    'Current Status': 'Recovered',
    Nationality: 'Italy',
    'Status Change Date': '29/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf08',
    },
    'Patient Number': '17',
    'Date Announced': '04/03/2020',
    'Age Bracket': '55',
    'Detected City': 'Gurugram',
    'Detected District': 'Italians',
    'Detected State': 'Haryana',
    'State code': 'HR',
    'Current Status': 'Recovered',
    Nationality: 'Italy',
    'Status Change Date': '29/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf09',
    },
    'Patient Number': '18',
    'Date Announced': '04/03/2020',
    'Age Bracket': '55',
    'Detected City': 'Gurugram',
    'Detected District': 'Italians',
    'Detected State': 'Haryana',
    'State code': 'HR',
    'Current Status': 'Recovered',
    Nationality: 'Italy',
    'Status Change Date': '29/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf0a',
    },
    'Patient Number': '19',
    'Date Announced': '04/03/2020',
    'Age Bracket': '55',
    'Detected City': 'Gurugram',
    'Detected District': 'Italians',
    'Detected State': 'Haryana',
    'State code': 'HR',
    'Current Status': 'Hospitalized',
    Nationality: 'Italy',
    'Status Change Date': '04/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf0b',
    },
    'Patient Number': '20',
    'Date Announced': '04/03/2020',
    'Age Bracket': '55',
    'Detected City': 'Gurugram',
    'Detected District': 'Italians',
    'Detected State': 'Haryana',
    'State code': 'HR',
    'Current Status': 'Hospitalized',
    Nationality: 'Italy',
    'Status Change Date': '04/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf0c',
    },
    'Patient Number': '21',
    'Date Announced': '04/03/2020',
    'Age Bracket': '70',
    Gender: 'F',
    'Detected City': 'Jaipur',
    'Detected District': 'Italians',
    'Detected State': 'Rajasthan',
    'State code': 'RJ',
    'Current Status': 'Recovered',
    Nationality: 'Italy',
    'Status Change Date': '04/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf0d',
    },
    'Patient Number': '22',
    'Date Announced': '04/03/2020',
    Gender: 'M',
    'Detected City': 'Agra',
    'Detected District': 'Agra',
    'Detected State': 'Uttar Pradesh',
    'State code': 'UP',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '04/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf0e',
    },
    'Patient Number': '23',
    'Date Announced': '04/03/2020',
    Gender: 'F',
    'Detected City': 'Agra',
    'Detected District': 'Agra',
    'Detected State': 'Uttar Pradesh',
    'State code': 'UP',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '15/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf0f',
    },
    'Patient Number': '24',
    'Date Announced': '04/03/2020',
    'Age Bracket': '45',
    Gender: 'F',
    'Detected City': 'Agra',
    'Detected District': 'Agra',
    'Detected State': 'Uttar Pradesh',
    'State code': 'UP',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '15/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf10',
    },
    'Patient Number': '25',
    'Date Announced': '04/03/2020',
    Gender: 'M',
    'Detected City': 'Agra',
    'Detected District': 'Agra',
    'Detected State': 'Uttar Pradesh',
    'State code': 'UP',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '15/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf11',
    },
    'Patient Number': '26',
    'Date Announced': '04/03/2020',
    'Age Bracket': '16',
    Gender: 'M',
    'Detected City': 'Agra',
    'Detected District': 'Agra',
    'Detected State': 'Uttar Pradesh',
    'State code': 'UP',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '15/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf12',
    },
    'Patient Number': '27',
    'Date Announced': '04/03/2020',
    'Detected City': 'Agra',
    'Detected District': 'Agra',
    'Detected State': 'Uttar Pradesh',
    'State code': 'UP',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '04/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf13',
    },
    'Patient Number': '28',
    'Date Announced': '04/03/2020',
    'Detected District': 'Agra',
    'Detected State': 'Uttar Pradesh',
    'State code': 'UP',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '04/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf14',
    },
    'Patient Number': '29',
    'State Patient Number': 'DL-P2',
    'Date Announced': '05/03/2020',
    'Age Bracket': '27',
    Gender: 'M',
    'Detected City': 'Janakpuri',
    'Detected District': 'South West Delhi',
    'Detected State': 'Delhi',
    'State code': 'DL',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '05/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf15',
    },
    'Patient Number': '30',
    'Date Announced': '05/03/2020',
    'Age Bracket': '59',
    Gender: 'M',
    'Detected City': 'Ghaziabad',
    'Detected District': 'Ghaziabad',
    'Detected State': 'Uttar Pradesh',
    'State code': 'UP',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '05/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf16',
    },
    'Patient Number': '31',
    'State Patient Number': 'DL-P3',
    'Date Announced': '06/03/2020',
    'Detected City': 'Uttam Nagar',
    'Detected District': 'West Delhi',
    'Detected State': 'Delhi',
    'State code': 'DL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '15/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf17',
    },
    'Patient Number': '32',
    'Date Announced': '07/03/2020',
    'Age Bracket': '65',
    Gender: 'M',
    'Detected City': 'Ladakh',
    'Detected District': 'Leh',
    'Detected State': 'Ladakh',
    'State code': 'LA',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '07/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf18',
    },
    'Patient Number': '33',
    'Date Announced': '07/03/2020',
    'Age Bracket': '75',
    Gender: 'M',
    'Detected City': 'Ladakh',
    'Detected District': 'Leh',
    'Detected State': 'Ladakh',
    'State code': 'LA',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '07/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf19',
    },
    'Patient Number': '34',
    'State Patient Number': 'TN-P1',
    'Date Announced': '07/03/2020',
    'Age Bracket': '45',
    Gender: 'M',
    'Detected City': 'Kancheepuram',
    'Detected District': 'Kancheepuram',
    'Detected State': 'Tamil Nadu',
    'State code': 'TN',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '07/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf1a',
    },
    'Patient Number': '35',
    'State Patient Number': 'KL-PT-P1',
    'Date Announced': '08/03/2020',
    'Age Bracket': '24',
    Gender: 'M',
    'Detected City': 'Ranni',
    'Detected District': 'Pathanamthitta',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '27/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf1b',
    },
    'Patient Number': '36',
    'State Patient Number': 'KL-PT-P1',
    'Date Announced': '08/03/2020',
    'Age Bracket': '54',
    Gender: 'M',
    'Detected City': 'Ranni',
    'Detected District': 'Pathanamthitta',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '29/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf1c',
    },
    'Patient Number': '37',
    'State Patient Number': 'KL-P1-P1',
    'Date Announced': '08/03/2020',
    'Age Bracket': '53',
    Gender: 'F',
    'Detected City': 'Ranni',
    'Detected District': 'Pathanamthitta',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '29/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf1d',
    },
    'Patient Number': '38',
    'State Patient Number': 'KL-PT-P2',
    'Date Announced': '08/03/2020',
    'Age Bracket': '65',
    Gender: 'M',
    'Detected City': 'Ranni',
    'Detected District': 'Pathanamthitta',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '29/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf1e',
    },
    'Patient Number': '39',
    'State Patient Number': 'KL-PT-P2',
    'Date Announced': '08/03/2020',
    'Age Bracket': '61',
    Gender: 'F',
    'Detected City': 'Ranni',
    'Detected District': 'Pathanamthitta',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '29/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf1f',
    },
    'Patient Number': '40',
    'State Patient Number': 'DL-P4',
    'Date Announced': '09/03/2020',
    'Age Bracket': '25',
    Gender: 'F',
    'Detected City': 'Tri Nagar',
    'Detected District': 'North Delhi',
    'Detected State': 'Delhi',
    'State code': 'DL',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '09/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf20',
    },
    'Patient Number': '41',
    'Date Announced': '09/03/2020',
    'Age Bracket': '63',
    Gender: 'F',
    'Detected City': 'Jammu',
    'Detected District': 'Jammu',
    'Detected State': 'Jammu and Kashmir',
    'State code': 'JK',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '09/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf21',
    },
    'Patient Number': '42',
    'State Patient Number': 'KA-P1',
    'Date Announced': '09/03/2020',
    'Age Bracket': '46',
    Gender: 'M',
    'Detected City': 'Bengaluru',
    'Detected District': 'Bengaluru Urban',
    'Detected State': 'Karnataka',
    'State code': 'KA',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '27/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf22',
    },
    'Patient Number': '43',
    'State Patient Number': 'KL-KN-1',
    'Date Announced': '09/03/2020',
    'Age Bracket': '3',
    Gender: 'M',
    'Detected City': 'Kannur',
    'Detected District': 'Kannur',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '26/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf23',
    },
    'Patient Number': '44',
    'Date Announced': '09/03/2020',
    Gender: 'M',
    'Detected City': 'Pune',
    'Detected District': 'Pune',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '25/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf24',
    },
    'Patient Number': '45',
    'Date Announced': '09/03/2020',
    Gender: 'F',
    'Detected City': 'Pune',
    'Detected District': 'Pune',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '25/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf25',
    },
    'Patient Number': '46',
    'State Patient Number': 'PJ-P1',
    'Date Announced': '09/03/2020',
    Gender: 'M',
    'Detected City': 'Amritsar',
    'Detected District': 'Amritsar',
    'Detected State': 'Punjab',
    'State code': 'PB',
    'Current Status': 'Hospitalized',
    Nationality: 'Italy',
    'Status Change Date': '09/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf26',
    },
    'Patient Number': '47',
    'Date Announced': '09/03/2020',
    'Age Bracket': '48',
    Gender: 'M',
    'Detected City': 'Agra',
    'Detected District': 'Agra',
    'Detected State': 'Uttar Pradesh',
    'State code': 'UP',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '20/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf27',
    },
    'Patient Number': '48',
    'Date Announced': '09/03/2020',
    'Detected City': 'Agra',
    'Detected District': 'Agra',
    'Detected State': 'Uttar Pradesh',
    'State code': 'UP',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '09/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf28',
    },
    'Patient Number': '49',
    'State Patient Number': 'KL-PT-P3',
    'Date Announced': '10/03/2020',
    'Detected City': 'Kozhencherry',
    'Detected District': 'Pathanamthitta',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '03/04/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf29',
    },
    'Patient Number': '50',
    'State Patient Number': 'KL-PT-P4',
    'Date Announced': '10/03/2020',
    'Detected City': 'Kozhencherry',
    'Detected District': 'Pathanamthitta',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '10/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf2a',
    },
    'Patient Number': '51',
    'State Patient Number': 'KA-P2',
    'Date Announced': '10/03/2020',
    'Age Bracket': '40',
    Gender: 'M',
    'Detected City': 'Bengaluru',
    'Detected District': 'Bengaluru Urban',
    'Detected State': 'Karnataka',
    'State code': 'KA',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '24/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf2b',
    },
    'Patient Number': '52',
    'State Patient Number': 'KA-P3',
    'Date Announced': '10/03/2020',
    'Age Bracket': '47',
    Gender: 'F',
    'Detected City': 'Bengaluru',
    'Detected District': 'Bengaluru Urban',
    'Detected State': 'Karnataka',
    'State code': 'KA',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '27/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf2c',
    },
    'Patient Number': '53',
    'State Patient Number': 'KA-P4',
    'Date Announced': '10/03/2020',
    'Age Bracket': '13',
    Gender: 'F',
    'Detected City': 'Bengaluru',
    'Detected District': 'Bengaluru Urban',
    'Detected State': 'Karnataka',
    'State code': 'KA',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '24/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf2d',
    },
    'Patient Number': '54',
    'State Patient Number': 'KL-EL-P1',
    'Date Announced': '10/03/2020',
    Gender: 'M',
    'Detected City': 'Kochi',
    'Detected District': 'Ernakulam',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '26/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf2e',
    },
    'Patient Number': '55',
    'State Patient Number': 'KL-EL-P2',
    'Date Announced': '10/03/2020',
    Gender: 'F',
    'Detected City': 'Kochi',
    'Detected District': 'Ernakulam',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '26/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf2f',
    },
    'Patient Number': '56',
    'State Patient Number': 'KL-PT-P5',
    'Date Announced': '10/03/2020',
    'Age Bracket': '96',
    Gender: 'M',
    'Detected City': 'Ranni',
    'Detected District': 'Pathanamthitta',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '31/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf30',
    },
    'Patient Number': '57',
    'State Patient Number': 'KL-PT-P6',
    'Date Announced': '10/03/2020',
    'Age Bracket': '89',
    Gender: 'F',
    'Detected City': 'Ranni',
    'Detected District': 'Pathanamthitta',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '31/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf31',
    },
    'Patient Number': '58',
    'State Patient Number': 'KL-KT-R1',
    'Date Announced': '10/03/2020',
    Gender: 'M',
    'Detected City': 'Chengalam',
    'Detected District': 'Kottayam',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '28/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf32',
    },
    'Patient Number': '59',
    'State Patient Number': 'KL-KT-R2',
    'Date Announced': '10/03/2020',
    Gender: 'F',
    'Detected City': 'Chengalam',
    'Detected District': 'Kottayam',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '28/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf33',
    },
    'Patient Number': '60',
    'Date Announced': '10/03/2020',
    'Age Bracket': '3',
    Gender: 'F',
    'Detected City': 'Pune',
    'Detected District': 'Pune',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '10/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf34',
    },
    'Patient Number': '61',
    'Date Announced': '10/03/2020',
    'Detected City': 'Pune',
    'Detected District': 'Pune',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '10/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf35',
    },
    'Patient Number': '62',
    'Date Announced': '10/03/2020',
    Gender: 'M',
    'Detected City': 'Pune',
    'Detected District': 'Pune',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '10/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf36',
    },
    'Patient Number': '63',
    'Date Announced': '10/03/2020',
    'Age Bracket': '85',
    Gender: 'M',
    'Detected City': 'Jaipur',
    'Detected District': 'Jaipur',
    'Detected State': 'Rajasthan',
    'State code': 'RJ',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '10/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf37',
    },
    'Patient Number': '64',
    'State Patient Number': 'DL-P5',
    'Date Announced': '11/03/2020',
    'Age Bracket': '46',
    Gender: 'M',
    'Detected City': 'Janakpuri',
    'Detected District': 'South West Delhi',
    'Detected State': 'Delhi',
    'State code': 'DL',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '24/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf38',
    },
    'Patient Number': '65',
    'Date Announced': '11/03/2020',
    Gender: 'M',
    'Detected City': 'Chuchot',
    'Detected District': 'Leh',
    'Detected State': 'Ladakh',
    'State code': 'LA',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '11/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf39',
    },
    'Patient Number': '66',
    'Date Announced': '11/03/2020',
    'Age Bracket': '70',
    Gender: 'M',
    'Detected City': 'Mumbai',
    'Detected District': 'Mumbai',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '11/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf3a',
    },
    'Patient Number': '67',
    'Date Announced': '11/03/2020',
    'Age Bracket': '68',
    Gender: 'F',
    'Detected City': 'Mumbai',
    'Detected District': 'Mumbai',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '11/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf3b',
    },
    'Patient Number': '68',
    'Date Announced': '11/03/2020',
    'Detected City': 'Pimpri-Chinchwad',
    'Detected District': 'Pune',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '11/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf3c',
    },
    'Patient Number': '69',
    'Date Announced': '11/03/2020',
    'Detected City': 'Pimpri-Chinchwad',
    'Detected District': 'Pune',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '11/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf3d',
    },
    'Patient Number': '70',
    'Date Announced': '11/03/2020',
    'Detected City': 'Pimpri-Chinchwad',
    'Detected District': 'Pune',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '11/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf3e',
    },
    'Patient Number': '78',
    'Date Announced': '11/03/2020',
    'Age Bracket': '45',
    Gender: 'M',
    'Detected City': 'Nagpur',
    'Detected District': 'Nagpur',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '12/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf3f',
    },
    'Patient Number': '71',
    'State Patient Number': 'AP-P1',
    'Date Announced': '12/03/2020',
    'Age Bracket': '27',
    Gender: 'M',
    'Detected City': 'Nellore',
    'Detected District': 'S.P.S. Nellore',
    'Detected State': 'Andhra Pradesh',
    'State code': 'AP',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '01/04/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf40',
    },
    'Patient Number': '72',
    'State Patient Number': 'DL-P6',
    'Date Announced': '12/03/2020',
    'Age Bracket': '69',
    Gender: 'F',
    'Detected City': 'Janakpuri',
    'Detected District': 'South West Delhi',
    'Detected State': 'Delhi',
    'State code': 'DL',
    'Current Status': 'Deceased',
    Nationality: 'India',
    'Status Change Date': '12/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf41',
    },
    'Patient Number': '73',
    'State Patient Number': 'KA-P5',
    'Date Announced': '12/03/2020',
    'Age Bracket': '26',
    Gender: 'M',
    'Detected City': 'Bengaluru',
    'Detected District': 'Bengaluru Urban',
    'Detected State': 'Karnataka',
    'State code': 'KA',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '20/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf42',
    },
    'Patient Number': '75',
    'State Patient Number': 'KL-KN-2',
    'Date Announced': '12/03/2020',
    'Detected City': 'Kannur',
    'Detected District': 'Kannur',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '23/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf43',
    },
    'Patient Number': '76',
    'State Patient Number': 'KL-TS-P1',
    'Date Announced': '12/03/2020',
    'Detected City': 'Thrissur',
    'Detected District': 'Thrissur',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '24/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf44',
    },
    'Patient Number': '77',
    'Date Announced': '12/03/2020',
    'Age Bracket': '65',
    Gender: 'M',
    'Detected City': 'Mumbai',
    'Detected District': 'Mumbai',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Deceased',
    Nationality: 'India',
    'Status Change Date': '12/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf45',
    },
    'Patient Number': '79',
    'Date Announced': '12/03/2020',
    'Age Bracket': '33',
    Gender: 'M',
    'Detected City': 'Pune',
    'Detected District': 'Pune',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '12/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf46',
    },
    'Patient Number': '80',
    'Date Announced': '12/03/2020',
    'Age Bracket': '33',
    Gender: 'M',
    'Detected District': 'Mumbai',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '12/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf47',
    },
    'Patient Number': '81',
    'Date Announced': '12/03/2020',
    Gender: 'F',
    'Detected City': 'Lucknow',
    'Detected District': 'Lucknow',
    'Detected State': 'Uttar Pradesh',
    'State code': 'UP',
    'Current Status': 'Hospitalized',
    Nationality: 'Canada',
    'Status Change Date': '12/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf48',
    },
    'Patient Number': '82',
    'Date Announced': '12/03/2020',
    'Age Bracket': '27',
    Gender: 'M',
    'Detected City': 'Ghaziabad',
    'Detected District': 'Ghaziabad',
    'Detected State': 'Uttar Pradesh',
    'State code': 'UP',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '12/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf49',
    },
    'Patient Number': '74',
    'State Patient Number': 'KA-P6',
    'Date Announced': '13/03/2020',
    'Age Bracket': '76',
    Gender: 'M',
    'Detected City': 'Kalaburagi',
    'Detected District': 'Kalaburagi',
    'Detected State': 'Karnataka',
    'State code': 'KA',
    'Current Status': 'Deceased',
    Nationality: 'India',
    'Status Change Date': '13/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf4a',
    },
    'Patient Number': '83',
    'State Patient Number': 'DL-P7',
    'Date Announced': '13/03/2020',
    Gender: 'M',
    'Detected City': 'Delhi',
    'Detected District': 'New Delhi',
    'Detected State': 'Delhi',
    'State code': 'DL',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '13/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf4b',
    },
    'Patient Number': '84',
    'Date Announced': '13/03/2020',
    'Detected City': 'Jammu',
    'Detected District': 'Jammu',
    'Detected State': 'Jammu and Kashmir',
    'State code': 'JK',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '13/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf4c',
    },
    'Patient Number': '85',
    'State Patient Number': 'KL-TV-R3',
    'Date Announced': '13/03/2020',
    'Detected City': 'Varkala',
    'Detected District': 'Thiruvananthapuram',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'Italy',
    'Status Change Date': '24/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf4d',
    },
    'Patient Number': '86',
    'State Patient Number': 'KL-TV-R1',
    'Date Announced': '13/03/2020',
    'Detected City': 'Nedumangad',
    'Detected District': 'Thiruvananthapuram',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '28/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf4e',
    },
    'Patient Number': '87',
    'State Patient Number': 'KL-TV-R2',
    'Date Announced': '13/03/2020',
    Gender: 'M',
    'Detected City': 'Thiruvananthapuram',
    'Detected District': 'Thiruvananthapuram',
    'Detected State': 'Kerala',
    'State code': 'KL',
    'Current Status': 'Recovered',
    Nationality: 'India',
    'Status Change Date': '13/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf4f',
    },
    'Patient Number': '88',
    'Date Announced': '13/03/2020',
    Gender: 'F',
    'Detected City': 'Nagpur',
    'Detected District': 'Nagpur',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '13/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf50',
    },
    'Patient Number': '89',
    'Date Announced': '13/03/2020',
    Gender: 'M',
    'Detected City': 'Nagpur',
    'Detected District': 'Nagpur',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '13/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf51',
    },
    'Patient Number': '90',
    'Date Announced': '13/03/2020',
    'Detected City': 'Pune',
    'Detected District': 'Pune',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '13/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf52',
    },
    'Patient Number': '91',
    'Date Announced': '13/03/2020',
    Gender: 'F',
    'Detected City': 'Agra',
    'Detected District': 'Agra',
    'Detected State': 'Uttar Pradesh',
    'State code': 'UP',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '13/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf53',
    },
    'Patient Number': '92',
    'Date Announced': '14/03/2020',
    'Detected City': 'Ahmednagar',
    'Detected District': 'Ahmednagar',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '14/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf54',
    },
    'Patient Number': '93',
    'Date Announced': '14/03/2020',
    Gender: 'F',
    'Detected City': 'Mumbai',
    'Detected District': 'Mumbai',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '14/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf55',
    },
    'Patient Number': '94',
    'Date Announced': '14/03/2020',
    Gender: 'M',
    'Detected City': 'Thane - Vashi',
    'Detected District': 'Thane',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '14/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf56',
    },
    'Patient Number': '95',
    'Date Announced': '14/03/2020',
    'Age Bracket': '37',
    Gender: 'M',
    'Detected City': 'Kalyan-Dombivali',
    'Detected District': 'Thane',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '14/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf57',
    },
    'Patient Number': '96',
    'Date Announced': '14/03/2020',
    'Age Bracket': '59',
    'Detected City': 'Panvel (Kamothe)',
    'Detected District': 'Raigad',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '14/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf58',
    },
    'Patient Number': '97',
    'Date Announced': '14/03/2020',
    'Detected City': 'Navi Mumbai',
    'Detected District': 'Thane',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '14/03/2020',
    'Num Cases': '1',
  },
  {
    _id: {
      $oid: '6079bfbfb20ea10beccecf59',
    },
    'Patient Number': '98',
    'Date Announced': '14/03/2020',
    'Age Bracket': '43',
    Gender: 'M',
    'Detected City': 'Nagpur',
    'Detected District': 'Nagpur',
    'Detected State': 'Maharashtra',
    'State code': 'MH',
    'Current Status': 'Hospitalized',
    Nationality: 'India',
    'Status Change Date': '14/03/2020',
    'Num Cases': '1',
  },
]
export default data
